package com.agriprocure.dto;

public enum RealtimeEventType {
    QUEUE_UPDATED,
    TOKEN_CALLED,
    TOKEN_UPDATED,
    BOOKING_CREATED,
    WEIGHMENT_COMPLETED,
    QUALITY_COMPLETED,
    PROCUREMENT_COMPLETED,
    PAYMENT_PROCESSED,
    SLOT_UPDATED,
    NOTIFICATION_CREATED
}
