package com.agriprocure.dto;

public enum RealtimeEventType {
    QUEUE_UPDATED,
    TOKEN_CALLED,
    TOKEN_UPDATED,
    TOKEN_STATUS_CHANGED,
    BOOKING_CREATED,
    BOOKING_UPDATED,
    WEIGHMENT_COMPLETED,
    QUALITY_COMPLETED,
    PROCUREMENT_COMPLETED,
    INTAKE_STATUS_UPDATED,
    PAYMENT_PROCESSED,
    PAYMENT_UPDATED,
    SLOT_UPDATED,
    NOTIFICATION_CREATED
}
